apiVersion: v2
appVersion: "2.7.7"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: A Python based monitoring and tracking tool for Plex Media Server
home: https://github.com/truecharts/apps/tree/master/charts/stable/tautulli
icon: https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/logo.png?raw=true
keywords:
- tautulli
- plex
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tautulli
sources:
- https://github.com/Tautulli/Tautulli
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
