apiVersion: v2
appVersion: "4.3.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: The Lounge, modern web IRC client designed for self-hosting
home: https://github.com/truecharts/apps/tree/master/charts/stable/thelounge
icon: https://avatars.githubusercontent.com/u/14336958?s=200&v=4
keywords:
- thelounge
- IRC
- The Lounge
- docker
- thelounge-docker
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: thelounge
sources:
- https://github.com/thelounge/thelounge
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
