apiVersion: v2
appVersion: "2.4.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- name: "promtail"
  condition: promtail.enabled
  repository: https://truecharts.org
  version: "1.0.10"
deprecated: false
description: "Loki: like Prometheus, but for logs."
home: https://github.com/truecharts/apps/tree/master/charts/stable/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
keywords:
- logs
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: loki
sources:
  - https://github.com/grafana/loki
type: application
version: 2.0.7
annotations:
  truecharts.org/catagories: |
    - logs
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
