apiVersion: v2
appVersion: "0.1.0.1083"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: A fork of Radarr to work with Books & AudioBooks
home: https://github.com/truecharts/apps/tree/master/charts/stable/readarr
icon: https://github.com/Readarr/Readarr/blob/develop/Logo/1024.png?raw=true
keywords:
- readarr
- torrent
- usenet
- AudioBooks
- ebooks
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: readarr
sources:
- https://github.com/Readarr/Readarr
- https://readarr.com
type: application
version: 9.0.29
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
