apiVersion: v2
appVersion: "0.66.6"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Allow external services to be used like Apps.
home: https://github.com/truecharts/apps/tree/master/charts/stable/external-service
icon: https://truecharts.org/_static/img/external-service-icon.png
keywords:
- external-service
- reverse-proxy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: external-service
sources:
- https://github.com/truecharts/apps/tree/master/charts/stable/external-service
type: application
version: 4.0.18
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
