apiVersion: v2
appVersion: "2009.1.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Booksonic is a platform for accessing the audibooks you own wherever
  you are
home: https://github.com/truechartsapps/tree/master/charts/stable/booksonic-air
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/booksonic-air.png
keywords:
- booksonic
- audiobook
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: booksonic-air
sources:
- https://github.com/popeen/Booksonic-Air
- https://hub.docker.com/r/linuxserver/booksonic-air
version: 4.0.21
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
