apiVersion: v2
appVersion: "1.18.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: P2P file synchronization application
home: https://github.com/truecharts/apps/tree/master/charts/stable/syncthing
icon: https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-128.png
keywords:
- syncthing
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: syncthing
sources:
- https://syncthing.net/
- https://github.com/syncthing/syncthing
- https://hub.docker.com/r/syncthing/syncthing
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
