apiVersion: v2
appVersion: "1.18.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: FreshRSS is a self-hosted RSS feed aggregator
home: https://github.com/truecharts/apps/tree/master/charts/stable/freshrss
icon: https://github.com/FreshRSS/FreshRSS/blob/master/docs/img/FreshRSS-logo.png?raw=true
keywords:
- freshrss
- rss
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: freshrss
sources:
- https://github.com/FreshRSS/FreshRSS
- https://hub.docker.com/r/linuxserver/freshrss
type: application
version: 9.0.23
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
