apiVersion: v2
appVersion: "2.0.12"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Hyperion is an opensource Bias or Ambient Lighting implementation
home: https://github.com/truechartsapps/tree/master/charts/stable/hyperion-ng
icon: https://avatars.githubusercontent.com/u/17778452?s=200&v=4
keywords:
- hyperion-ng
- hyperion
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hyperion-ng
sources:
- https://github.com/hyperion-project/hyperion.ng
- https://hub.docker.com/r/sirfragalot/hyperion.ng
version: 4.0.21
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
