apiVersion: v2
appVersion: "0.8.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Focalboard is an open source, self-hosted alternative to Trello, Notion,
  and Asana.
home: https://github.com/truechartsapps/tree/master/charts/stable/focalboard
icon: https://github.com/mattermost/focalboard/raw/main/webapp/static/favicon.svg
keywords:
- focalboard
- kanban
- project management
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: focalboard
sources:
- https://www.focalboard.com/
- https://github.com/mattermost/focalboard
- https://github.com/FlipEnergy/container-images/blob/main/focalboard
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
