apiVersion: v2
appVersion: "1.5.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Create live TV channel streams from media on your Plex servers.
home: https://github.com/truechartsapps/tree/master/charts/stable/dizquetv
icon: https://github.com/vexorian/dizquetv/raw/main/resources/dizquetv.png?raw=true
keywords:
- dizqueTV
- dizquetv
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: dizquetv
sources:
- https://github.com/vexorian/dizquetv
- https://hub.docker.com/r/vexorian/dizquetv
version: 4.0.18
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
