apiVersion: v2
appVersion: "1.2.0-rcgi"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A remote desktop client written in GTK
home: https://github.com/truecharts/apps/tree/master/charts/stable/remmina
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/remmina-icon.png
keywords:
- remina
- remote
- desktop
- client
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: remmina
sources:
- https://github.com/linuxserver/docker-remmina
- https://remmina.org/
type: application
version: 1.0.23
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
