apiVersion: v2
appVersion: "1.2.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: The open source VNC client
home: https://github.com/truecharts/apps/tree/master/charts/stable/novnc
icon: https://github.com/truecharts/apps/raw/main/images/novnc.png
keywords:
- novnc
- vnc
- remote
- desktop
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: novnc
sources:
- https://novnc.com/
type: application
version: 1.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
