apiVersion: v2
appVersion: "0.8.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A free cross platform open source file manager with two panels side by
  side.
home: https://github.com/truecharts/apps/tree/master/charts/stable/doublecommander
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/doublecommander-icon.png
keywords:
- doublecommander
- file
- manager
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: doublecommander
sources:
- https://github.com/linuxserver/docker-doublecommander
- https://doublecmd.sourceforge.io/
type: application
version: 2.0.22
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
