apiVersion: v2
appVersion: "8.3.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.
home: https://github.com/truecharts/apps/tree/master/charts/stable/grafana
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
  - analytics
  - monitoring
  - metrics
  - logs
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: grafana
sources:
  - https://github.com/bitnami/bitnami-docker-grafana
  - https://grafana.com/
type: application
version: 1.0.12
annotations:
  truecharts.org/catagories: |
    - metrics
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
