apiVersion: v2
appVersion: "0.20.95"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://github.com/truecharts/apps/tree/master/charts/stable/jackett
icon: https://truecharts.org/_static/img/jackett-icon.png
keywords:
- jackett
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jackett
sources:
- https://github.com/Jackett/Jackett
type: application
version: 9.0.40
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
