apiVersion: v2
appVersion: "2.2.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: An Application dashboard and launcher
home: https://github.com/truecharts/apps/tree/master/charts/stable/heimdall
icon: https://i.imgur.com/mM4tcO5.png
keywords:
- heimdall
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: heimdall
sources:
- https://github.com/linuxserver/Heimdall/
type: application
version: 9.0.24
annotations:
  truecharts.org/catagories: |
    - organizers
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
