apiVersion: v2
appVersion: "0.9.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Web-based LDAP browser to manage your LDAP server
home: https://github.com/truecharts/apps/tree/master/charts/stable/phpldapadmin
icon: https://repository-images.githubusercontent.com/3665191/dd213f80-766c-11e9-8117-6b639095ef99
keywords:
- phpldapadmin
- openldap
- userrights
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: phpldapadmin
sources:
- https://gitlab.v2.rancher.geohub.space/g3s/i3s/i3s-helm-catalog
type: application
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - management
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
