apiVersion: v2
appVersion: "4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: pretend-youre-xyzzy, a cards against humanity clone
home: https://github.com/truechartsapps/tree/master/charts/stable/pretend-youre-xyzzy
icon: https://apk-google.com/wp-content/uploads/2020/12/Client-for-Pretend-Youre-Xyzzy-open-source-5.0.1.png
keywords:
- pretend-youre-xyzzy
- cards
- against
- humanity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pretend-youre-xyzzy
sources:
- https://github.com/ajanata/PretendYoureXyzzy
- https://github.com/emcniece/DockerYourXyzzy
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
