apiVersion: v2
appVersion: "3.0.23"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: OpenSource Radius implementation
home: https://www.openldap.org
icon: https://networkradius.com/assets/img/FR-NR.svg
keywords:
- radius
- auth
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: freeradius
sources:
- https://hub.docker.com/r/freeradius/freeradius-server/
- https://freeradius.org/
type: application
version: 4.0.21
annotations:
  truecharts.org/catagories: |
    - auth
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
