apiVersion: v2
appVersion: "3.4.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Free and easy binary newsreader
home: https://github.com/truecharts/apps/tree/master/charts/stable/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
keywords:
- sabnzbd
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sabnzbd
sources:
- https://sabnzbd.org/
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
