apiVersion: v2
appVersion: "3.00"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://github.com/truecharts/apps/tree/master/charts/stable/transmission
icon: https://upload.wikimedia.org/wikipedia/commons/6/6d/Transmission_icon.png
keywords:
- transmission
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: transmission
sources:
- https://github.com/transmission/transmission
- https://hub.docker.com/r/linuxserver/transmission
type: application
version: 9.0.21
annotations:
  truecharts.org/catagories: |
    - download-tools
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
