apiVersion: v2
appVersion: "3.5.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.26
description: "Straightforward open source project management system to make your ideas reality."
home: https://github.com/truechartsapps/tree/master/charts/stable/monica
icon: https://pbs.twimg.com/profile_images/951820722191720450/mtCNuIXX.jpg
keywords:
- crm
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: monica
sources:
- https://github.com/monicahq/monica
- https://hub.docker.com/_/monica
version: 0.0.10
annotations:
  truecharts.org/catagories: |
    - crm
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
