apiVersion: v2
appVersion: "1.7.18"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A Fast, Simple, and Flexible, file-based Web-platform.
home: https://github.com/truecharts/apps/tree/master/charts/stable/grav
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grav-logo.png
keywords:
- grav
- web
- platform
- file
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: grav
sources:
- https://github.com/linuxserver/docker-grav
- https://github.com/getgrav/grav/
type: application
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
