apiVersion: v2
appVersion: "4.0.1482"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
home: https://github.com/truecharts/apps/tree/master/charts/stable/ombi
icon: https://raw.githubusercontent.com/Ombi-app/Ombi/gh-pages/img/android-chrome-512x512.png
keywords:
- ombi
- plex
- emby
- sonarr
- radarr
- couchpotato
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ombi
sources:
- https://github.com/tidusjar/Ombi
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
