apiVersion: v2
appVersion: "minimal"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Private Windows Activation Server for development and testing
home: https://github.com/truecharts/apps/tree/master/charts/stable/kms
icon: https://truecharts.org/_static/img/kms-icon.jpg
keywords:
- kms
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: kms
sources:
- https://github.com/SystemRage/py-kms
type: application
version: 9.0.23
annotations:
  truecharts.org/catagories: |
    - graywares
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
