apiVersion: v2
appVersion: "2021.11.5"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.23
deprecated: false
description: home-assistant App for TrueNAS SCALE
home: https://github.com/truecharts/apps/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
keywords:
- home-assistant
- hass
- homeassistant
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: home-assistant
sources:
- https://github.com/home-assistant/home-assistant
- https://github.com/cdr/code-server
type: application
version: 12.0.11
annotations:
  truecharts.org/catagories: |
    - home-automation
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
