apiVersion: v2
appVersion: "1.15.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: ownCloud Infinite Scale is a self-hosted file sync and share server.
home: https://github.com/truechartsapps/tree/master/charts/stable/owncloud-ocis
icon: https://avatars.githubusercontent.com/u/1645051?s=200&v=4
keywords:
- owncloud
- ocis
- infinite
- scale
- self-hosted
- sync
- share
- server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: owncloud-ocis
sources:
- https://hub.docker.com/r/owncloud/ocis
- https://owncloud.dev/ocis/
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
