apiVersion: v2
appVersion: "1.0.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: A self-hosted podcast manager to download episodes as soon as they become
  live.
home: https://github.com/truecharts/apps/tree/master/charts/stable/podgrab
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Podcasts_%28iOS%29.svg/1024px-Podcasts_%28iOS%29.svg.png
keywords:
- podgrab
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: podgrab
sources:
- https://github.com/akhilrex/podgrab
- https://hub.docker.com/r/akhilrex/podgrab
type: application
version: 7.0.19
annotations:
  truecharts.org/catagories: |
    - mutlimedia
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
