apiVersion: v2
appVersion: "0.8.8"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.26
- condition: redis.enabled
  name: redis
  repository: https://truecharts.org
  version: 1.0.28
description: "Protect your email from spam using disposable addresses."
home: https://github.com/truechartsapps/tree/master/charts/stable/anonaddy
icon: https://avatars.githubusercontent.com/u/51450862?s=200&v=4?sanitize=true
keywords:
- anonaddy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: anonaddy
sources:
- https://github.com/anonaddy/docker
version: 6.0.10
annotations:
  truecharts.org/catagories: |
    - email
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
