apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: HTPC/Homelab Services Organizer
home: https://github.com/truecharts/apps/tree/master/charts/stable/organizr
icon: https://github.com/causefx/Organizr/blob/v2-master/plugins/images/organizr/logo.png?raw=true
keywords:
- organizr
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: organizr
sources:
- https://github.com/causefx/Organizr
- https://hub.docker.com/r/organizr/organizr
type: application
version: 9.0.20
annotations:
  truecharts.org/catagories: |
    - organizers
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
