apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Easy platform to combine all your social links
home: https://github.com/truecharts/apps/tree/master/charts/stable/littlelink
icon: https://littlelink.io/images/avatar@2x.png
keywords:
- littlelink
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: littlelink
sources:
- https://github.com/techno-tim/littlelink-server
- https://github.com/sethcottle/littlelink
type: application
version: 4.0.28
annotations:
  truecharts.org/catagories: |
    - social
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
