apiVersion: v2
appVersion: "1.23.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.23
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://github.com/truecharts/apps/tree/master/charts/stable/vaultwarden
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png
keywords:
- bitwarden
- bitwardenrs
- bitwarden_rs
- vaultwarden
- password
- rust
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vaultwarden
sources:
- https://github.com/dani-garcia/vaultwarden
type: application
version: 13.0.10
annotations:
  truecharts.org/catagories: |
    - security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
