apiVersion: v2
appVersion: "6.0.3"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS
  and Vue
home: https://github.com/truecharts/apps/tree/master/charts/stable/zwavejs2mqtt
icon: https://raw.githubusercontent.com/zwave-js/zwavejs2mqtt/master/static/logo.png
keywords:
- zwavejs2mqtt
- zwave-js
- z-wave
- zwave
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: zwavejs2mqtt
sources:
- https://github.com/zwave-js/zwavejs2mqtt
- https://hub.docker.com/r/zwavejs/zwavejs2mqtt
type: application
version: 9.0.23
annotations:
  truecharts.org/catagories: |
    - tools
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
