apiVersion: v2
appVersion: "3.12.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A high quality, visual, open source tool to create, design, and edit
  database files compatible with SQLite
home: https://github.com/truecharts/apps/tree/master/charts/stable/sqlitebrowser
icon: https://sqlitebrowser.org/images/sqlitebrowser.svg
keywords:
- sqlite
- browser
- sqlitebrowser
- database
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sqlitebrowser
sources:
- https://github.com/linuxserver/docker-sqlitebrowser
- https://sqlitebrowser.org/
type: application
version: 1.0.23
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
