apiVersion: v2
appVersion: "4.3.6"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Lychee is a free photo-management tool, which runs on your server or
  web-space
home: https://github.com/truecharts/apps/tree/master/charts/stable/lychee
icon: https://github.com/LycheeOrg/Lychee/blob/master/Banner.png?raw=true
keywords:
- lychee
- photo
- pictures
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: lychee
sources:
- https://github.com/LycheeOrg/Lychee
- https://hub.docker.com/r/lycheeorg/lychee
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
