apiVersion: v2
appVersion: "11693"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Open Source Conditional Access Module software
home: https://github.com/truecharts/apps/tree/master/charts/stable/oscam
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/oscam-logo.png
keywords:
- oscam
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: oscam
sources:
- https://trac.streamboard.tv/oscam/browser/trunk
type: application
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - DIY
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
