apiVersion: v2
appVersion: "2.1.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Node-RED is low-code programming for event-driven applications
home: https://github.com/truecharts/apps/tree/master/charts/stable/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
keywords:
- node-red
- nodered
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: node-red
sources:
- https://github.com/node-red/node-red-docker
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - tools
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
