apiVersion: v2
appVersion: "1.7.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: JDownloader is a free, open-source download management tool with a huge
  community of developers that makes downloading as easy and fast as it should be.
home: https://github.com/truecharts/apps/tree/master/charts/stable/jackett
icon: https://jdownloader.org/_media/knowledge/wiki/jdownloader.png?w=150
keywords:
- jdownloader
- download
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jdownloader2
sources:
- https://github.com/jlesage/docker-jdownloader-2
- https://hub.docker.com/r/jlesage/jdownloader-2
- https://jdownloader.org/
type: application
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - downloads
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
