apiVersion: v2
appVersion: "1.5.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Community developed LDAP software
home: https://www.openldap.org
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Database-openldap.svg/640px-Database-openldap.svg.png
keywords:
- ldap
- openldap
- iam-stack
- high availability
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: openldap
sources:
- https://github.com/jp-gouin/helm-openldap
- https://github.com/osixia/docker-openldap
type: application
version: 4.0.24
annotations:
  truecharts.org/catagories: |
    - cloud
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
