apiVersion: v2
appVersion: "4.7.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Flood is a monitoring service for various torrent clients
home: https://github.com/truechartsapps/tree/master/charts/stable/flood
icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
keywords:
- flood
- rtorrent
- qbittorrent
- transmission
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: flood
sources:
- https://github.com/jesec/flood
- https://hub.docker.com/r/jesec/flood
version: 4.0.18
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
