apiVersion: v2
appVersion: "3.1.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: ERP beyond your fridge - grocy is a web-based self-hosted groceries &
  household management solution for your home
home: https://github.com/truecharts/apps/tree/master/charts/stable/grocy
icon: https://github.com/grocy/grocy/raw/master/public/img/appicons/mstile-150x150.png
keywords:
- grocy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: grocy
sources:
- https://github.com/grocy/grocy
type: application
version: 9.0.20
annotations:
  truecharts.org/catagories: |
    - Home-Automation
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
