apiVersion: v2
appVersion: "21.11.2021"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.26
description: "A simple, self-hosted, easy-to-use platform for organising and storing information."
home: https://github.com/truechartsapps/tree/master/charts/stable/bookstack
icon: https://avatars3.githubusercontent.com/u/20912696?s=400&v=4?sanitize=true
keywords:
  - bookstack
  - book
  - stack
  - organizer
  - server
  - hosted
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: bookstack
sources:
  - https://www.bookstackapp.com/
  - https://hub.docker.com/r/linuxserver/bookstack
version: 0.0.9
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
