apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.23
description: "Lightweight self-hosted facebook-styled PHP blog."
home: https://github.com/truechartsapps/tree/master/charts/stable/blog
icon: https://demo.photoprism.org/static/img/logo-avatar.svg
keywords:
  - blog
  - php
  - self
  - hosted
  - facebook
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: blog
sources:
  - https://github.com/m1k1o/blog
  - https://github.com/nicholaswilde/docker-blog
version: 0.0.8
annotations:
  truecharts.org/catagories: |
    - hosting
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
