apiVersion: v2
appVersion: "0.8.8"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Gaps searches through your Plex Server or local folders for all movies,
  then queries for known movies in the same collection.
home: https://github.com/truecharts/apps/tree/master/charts/stable/gaps
icon: https://raw.githubusercontent.com/JasonHHouse/gaps/master/images/Final-Black.png
keywords:
- gaps
- plex
- plex-media-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gaps
sources:
- https://github.com/JasonHHouse/gaps
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
