apiVersion: v2
appVersion: "2.0.14"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Eclipse Mosquitto - An open source MQTT broker
home: https://github.com/truecharts/apps/tree/master/charts/stable/mosquitto
icon: https://projects.eclipse.org/sites/default/files/mosquitto-200px.png
keywords:
- mosquitto
- MQTT
- eclipse-iot
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mosquitto
sources:
- https://github.com/eclipse/mosquitto
type: application
version: 4.0.21
annotations:
  truecharts.org/catagories: |
    - homeautomation
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
