apiVersion: v2
appVersion: "0.20.95"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Advanced tool to create your own TrueCharts-based App
home: https://github.com/truecharts/apps/tree/master/charts/stable/custom-app
icon: https://truecharts.org/_static/img/custom-app-icon.png
keywords:
- custom
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: custom-app
sources:
- https://github.com/truecharts/apps/tree/master/charts/stable/custom-app
type: application
version: 3.0.31
annotations:
  truecharts.org/catagories: |
    - custom
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
