apiVersion: v2
appVersion: "1.0.0.2372"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Looks and smells like Sonarr but made for music
home: https://github.com/truecharts/apps/tree/master/charts/stable/lidarr
icon: https://avatars3.githubusercontent.com/u/28475832?s=400&v=4
keywords:
- lidarr
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: lidarr
sources:
- https://github.com/Lidarr/Lidarr
type: application
version: 9.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
