apiVersion: v2
appVersion: "3.12.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Run VS Code on any machine anywhere and access it in the browser.
home: https://github.com/truecharts/apps/tree/master/charts/stable/code-server
icon: https://github.com/truecharts/apps/raw/main/images/code-server.jpg
keywords:
- code
- vs
- visual studio
- vscode
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: code-server
sources:
- https://github.com/cdr/code-server
type: application
version: 2.1.1
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
