apiVersion: v2
appVersion: "0.25.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Provides management of TV shows and/or Anime, it detects new episodes,
  links downloader apps, and more
home: https://github.com/truecharts/apps/tree/master/charts/stable/sickgear
icon: https://avatars.githubusercontent.com/u/9690267?s=200&v=4
keywords:
- sickgear
- manager
- tv
- shows
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sickgear
sources:
- https://github.com/linuxserver/docker-sickgear
- https://github.com/SickGear/SickGear
type: application
version: 1.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
