apiVersion: v2
appVersion: "1.7.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: OctoPrint is the snappy web interface for your 3D printer
home: https://github.com/truechartsapps/tree/master/charts/stable/octoprint
icon: https://avatars3.githubusercontent.com/u/5982294?s=400&v=4
keywords:
- octoprint
- 3d
- printer
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: octoprint
sources:
- https://github.com/OctoPrint/OctoPrint
- https://hub.docker.com/r/octoprint/octoprint
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
