apiVersion: v2
appVersion: "3.51.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A Helm chart for Kubernetes
home: https://github.com/truecharts/apps/tree/master/charts/stable/filezilla
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/filezilla-logo.png
keywords:
- filezilla
- ftp
- sftp
- ftps
- client
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: filezilla
sources:
- https://filezilla-project.org/
- https://github.com/linuxserver/docker-filezilla
type: application
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
