apiVersion: v2
appVersion: "0.1.8"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: A Helm chart for the k8s_gateway CoreDNS plugin
home: https://github.com/truecharts/apps/tree/master/charts/stable/k8s-gateway
icon: https://cncf-branding.netlify.app/img/projects/coredns/icon/black/coredns-icon-black.png
keywords:
- DNS
- networking
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: k8s-gateway
sources:
- https://github.com/ori-edge/k8s_gateway
type: application
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
