apiVersion: v2
appVersion: "63784405"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: TVheadend - a TV streaming server and digital video recorder
home: https://github.com/truecharts/apps/tree/master/charts/stable/tvheadend
icon: https://avatars.githubusercontent.com/u/1908588?s=200&v=4
keywords:
- tvheadend
- tv
- streaming
- dvb
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tvheadend
sources:
- https://github.com/tvheadend/tvheadend
type: application
version: 10.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
