apiVersion: v2
appVersion: "1.24.5.517"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Plex Media Server
home: https://github.com/truecharts/apps/tree/master/charts/stable/plex
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
keywords:
- plex
- plex-media-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: plex
sources:
- https://github.com/k8s-at-home/container-images/pkgs/container/plex
type: application
version: 8.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
