apiVersion: v2
appVersion: "2.0.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: FlareSolverr is a proxy server to bypass Cloudflare protection
home: https://github.com/truechartsapps/tree/master/charts/stable/flaresolverr
icon: https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.svg
keywords:
- flaresolverr
- jackett
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: flaresolverr
sources:
- https://github.com/FlareSolverr/FlareSolverr
- https://hub.docker.com/r/flaresolverr/flaresolverr
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
