apiVersion: v2
appVersion: "0.90.74"
description: Status page for monitoring your websites and applications
name: statping
version: 4.0.10
kubeVersion: ">=1.16.0-0"
keywords:
- statping
- status
- status-page
home: https://github.com/truecharts/apps/tree/master/charts/stable/statping
icon: https://avatars.githubusercontent.com/u/61949049?s=200&v=4
sources:
- https://github.com/statping/statping
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.23
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
