apiVersion: v2
appVersion: "3.18.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: true
description: Usenet meta search
home: https://github.com/truecharts/apps/tree/master/charts/stable/nzbhydra
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
keywords:
- nzbhydra
- usenet
kubeVersion: '>=1.16.0-0'
maintainers: []
name: nzbhydra
sources:
- https://github.com/theotherp/nzbhydra2
type: application
version: 9.0.22
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
