apiVersion: v2
appVersion: "1.1.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.13
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.25
description: "A web-based dashboard application that gives you a neat and clean interface for logging your fuel fill-ups for all of your vehicles."
home: https://github.com/truechartsapps/tree/master/charts/stable/clarkson
icon: "https://github.com/linuxserver/Clarkson/raw/master/src/mstile-150x150.png"
keywords:
  - fuel
  - car
  - log
  - fill-up
  - vehicle
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: clarkson
sources:
  - https://github.com/linuxserver/Clarkson
  - https://hub.docker.com/r/linuxserver/clarkson
version: 0.0.9
annotations:
  truecharts.org/catagories: |
    - vehicle
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
