image:
  repository: tccr.io/truecharts/clarkson
  pullPolicy: IfNotPresent
  tag: v1.1.2@sha256:27051a894950310536f41a9f84d6a7da79ac856871f9b2e61be702f963afffd4

strategy:
  type: Recreate

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false


podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10113
        targetPort: 3000

# See more environment variables in the clarkson documentation
# https://github.com/linuxserver/docker-clarkson#parameters
env:
  PUID: 568
  MYSQL_USERNAME: clarkson


envValueFrom:
  MYSQL_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  MYSQL_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

persistence:
  varrun:
    enabled: true

mariadb:
  enabled: true
  mariadbUsername: clarkson
  mariadbDatabase: clarkson
  existingSecret: "mariadbcreds"
