apiVersion: v2
appVersion: "0.0.10"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Take control over your live stream video by running it yourself. Streaming
  + chat out of the box.
home: https://github.com/truechartsapps/tree/master/charts/stable/owncast
icon: https://owncast.online/images/owncast-logo-1000x1000.png
keywords:
- owncast
- stream
- open source
- chat
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: owncast
sources:
- https://owncast.online/
- https://github.com/owncast/owncast
version: 4.0.18
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
