apiVersion: v2
appVersion: "1.3.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A simple null file http and https server
home: https://github.com/truechartsapps/tree/master/charts/stable/nullserv
icon: https://miro.medium.com/max/800/1*UL9RWkTUtJlyHW7kGm20hQ.png
keywords:
- nullserv
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: nullserv
sources:
- https://github.com/bmrzycki/nullserv
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
