apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Serial to Socket Redirector
home: https://github.com/truechartsapps/tree/master/charts/stable/ser2sock
icon: https://i.imgur.com/GfZ7McO.png
keywords:
- ser2sock
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ser2sock
sources:
- https://github.com/nutechsoftware/ser2sock
- https://github.com/tenstartups/ser2sock
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
