apiVersion: v2
appVersion: "0.14.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Music streaming server / subsonic server API implementation
home: https://github.com/truechartsapps/tree/master/charts/stable/gonic
icon: https://raw.githubusercontent.com/sentriz/gonic/master/.github/logo.png
keywords:
- music
- subsonic
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gonic
sources:
- https://github.com/sentriz/gonic
- https://hub.docker.com/r/sentriz/gonic
version: 4.0.18
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
