apiVersion: v2
appVersion: "0.134.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A comics/mangas server to serve/stream pages via API
home: https://github.com/truechartsapps/tree/master/charts/stable/komga
icon: https://komga.org/assets/media/logo.svg
keywords:
- komga
- comics
- mangas
- server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: komga
sources:
- https://komga.org/
- https://github.com/gotson/komga
version: 4.0.25
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
