apiVersion: v2
appVersion: "2.5.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Test App for Traefik
home: https://github.com/truecharts/apps/tree/master/charts/stable/traefik
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
- https://traefik.io/
type: application
version: 10.0.22
annotations:
  truecharts.org/catagories: |
    - network
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
