apiVersion: v2
appVersion: "1.0.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Bazarr is a companion application to Sonarr and Radarr. It manages and
  downloads subtitles based on your requirements
home: https://github.com/truecharts/apps/tree/master/charts/stable/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
keywords:
- bazarr
- radarr
- sonarr
- subtitles
- usenet
- torrent
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: bazarr
sources:
- https://github.com/morpheus65535/bazarr
- https://hub.docker.com/r/linuxserver/bazarr
type: application
version: 9.0.21
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
