apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: aria server for downloading web content
home: https://github.com/truecharts/apps/tree/master/charts/stable/aira2
icon: https://avatars.githubusercontent.com/u/13545224?s=200&v=4
keywords:
- aria2
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: aria2
sources:
- https://github.com/P3TERX/Aria2-Pro-Docker
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
