apiVersion: v2
appVersion: "3.3.3"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.26
description: "XBackBone is a simple, self-hosted, lightweight PHP file manager"
home: https://github.com/truechartsapps/tree/master/charts/stable/xbackbone
icon: https://github.com/SergiX44/XBackBone/raw/master/.github/xbackbone.png
keywords:
- xbackbone
- xshare
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: xbackbone
sources:
- https://github.com/SergiX44/XBackBone
- https://hub.docker.com/r/pe46dro/xbackbone-docker
version: 0.0.8
annotations:
  truecharts.org/catagories: |
    - files
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
