apiVersion: v2
appVersion: "ee8a20c"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: A self-hosted static file serving app which does nothing more than just
  serve up static files from a mounted volume.
home: https://github.com/truecharts/apps/tree/master/charts/stable/static
icon: ''
keywords:
- app
- web
- filesystem
- static
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: static
sources:
- https://github.com/prologic/static
- https://github.com/nicholaswilde/docker-static
type: application
version: 1.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
