apiVersion: v2
appVersion: "2.13.01"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: deCONZ is an easy to use control software, with which you can set up
  and control Zigbee networks of any size without further programming effort.
home: https://github.com/truechartsapps/tree/master/charts/stable/deconz
icon: https://avatars1.githubusercontent.com/u/4217524?s=400&v=4
keywords:
- deconz
- home-automation
- zigbee
- conbee
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: deconz
sources:
- https://github.com/dresden-elektronik/deconz-rest-plugin
- https://github.com/marthoc/docker-deconz
version: 5.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
