apiVersion: v2
appVersion: "1.22.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Bridges events and allows you to control your Zigbee devices via MQTT
home: https://github.com/truecharts/apps/tree/master/charts/stable/zigbee2mqtt
icon: https://www.zigbee2mqtt.io/images/logo.png
keywords:
- zigbee
- mqtt
- home-assistant
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: zigbee2mqtt
sources:
- https://github.com/Koenkk/zigbee2mqtt
version: 1.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
