apiVersion: v2
appVersion: "2.0.3"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Deluge App for TrueNAS SCALE
home: https://github.com/truecharts/apps/tree/master/charts/stable/deluge
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
keywords:
- transmission
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: deluge
sources:
- https://github.com/deluge-torrent/deluge
type: application
version: 9.0.20
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
