apiVersion: v2
appVersion: "0.47.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Navidrome is an open source web-based music collection server and streamer
home: https://github.com/truecharts/apps/tree/master/charts/stable/navidrome
icon: https://raw.githubusercontent.com/navidrome/navidrome/v0.42.0/ui/src/icons/android-icon-192x192.png
keywords:
- navidrome
- music
- streaming
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: navidrome
sources:
- https://github.com/deluan/navidrome
- https://hub.docker.com/r/deluan/navidrome
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
