apiVersion: v2
appVersion: "2.0.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Aggregated management of TrueNAS devices
home: https://github.com/truecharts/apps/tree/master/charts/stable/truecommand
icon: https://www.ixsystems.com/documentation/truecommand/1.2/_static/tv-logo.png
keywords:
- truecommand
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: truecommand
sources:
- https://hub.docker.com/r/ixsystems/truecommand
type: application
version: 9.0.19
annotations:
  truecharts.org/catagories: |
    - Administration
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
