apiVersion: v2
appVersion: "5.2.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Librespeed is a HTML5 webpage to test upload and download speeds
home: https://github.com/truechartsapps/tree/master/charts/stable/librespeed
icon: https://github.com/librespeed/speedtest/blob/master/.logo/icon_huge.png?raw=true
keywords:
- librespeed
- speedtest
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: librespeed
sources:
- https://github.com/librespeed/speedtest
- https://hub.docker.com/r/linuxserver/librespeed
- https://github.com/truechartsapps/tree/master/charts/librespeed
version: 4.0.23
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
