apiVersion: v2
appVersion: "1.8.0"
version: 5.0.10
kubeVersion: '>=1.16.0-0'
name: firefox-syncserver
description: This is an all-in-one package for running a self-hosted Firefox Sync server.
type: application
home: "https://github.com/truecharts/apps/tree/main/charts/firefox-syncserver"
icon: "https://upload.wikimedia.org/wikipedia/en/0/01/Firefox_Sync_logo.png"
keywords:
  - server
  - sync
  - syncserver
  - firefox
sources:
  - https://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync-1.5.html
  - https://hub.docker.com/r/crazymax/firefox-syncserver
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.23
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
