apiVersion: v2
appVersion: "0.5.3"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Mylar is a automated Comic Book downloader
home: https://github.com/truechartsapps/tree/master/charts/stable/mylar
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mylar-icon.png
keywords:
- mylar
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mylar
sources:
- https://github.com/mylar3/mylar3
- https://github.com/linuxserver/docker-mylar3
- https://github.com/truechartsapps/tree/master/charts/mylar
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
