apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Valheim dedicated gameserver with automatic update and world backup support
home: https://github.com/truecharts/apps/tree/master/charts/stable/valheim
icon: https://raw.githubusercontent.com/lloesche/valheim-server-docker/main/misc/Logo_valheim.png
keywords:
- valheim
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: valheim
sources:
- https://github.com/lloesche/valheim-server-docker
- https://hub.docker.com/r/lloesche/valheim-server
version: 1.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
