apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Simple text sharing
home: https://github.com/truecharts/apps/tree/master/charts/stable/haste
icon: https://raw.githubusercontent.com/nicholaswilde/helm-charts/main/images/haste.png
keywords:
- haste
- hastebin
- haste-server
- pastebin
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: haste-server
sources:
- https://github.com/seejohnrun/haste-server
- https://github.com/k8s-at-home/container-images
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
