apiVersion: v2
appVersion: "5de90278"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: pyLoad is a Free and Open Source download manager written in Python and
  designed to be extremely lightweight, easily extensible and fully manageable via
  web.
home: https://github.com/truechartsapps/tree/master/charts/stable/pyload
icon: https://avatars.githubusercontent.com/u/3521496?s=200&v=4
keywords:
- pyload
- download
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pyload
sources:
- https://github.com/pyload/pyload
- https://hub.docker.com/r/linuxserver/pyload
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
