apiVersion: v2
appVersion: "2.1.7"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: mariadb.enabled
  name: mariadb
  repository: https://truecharts.org/
  version: 1.0.26
description: "Straightforward open source project management system to make your ideas reality."
home: https://github.com/truechartsapps/tree/master/charts/stable/leantime
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/leantime.jpg"
keywords:
  - leantime
  - project
  - management
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: leantime
sources:
  - https://leantime.io/
  - https://hub.docker.com/r/nicholaswilde/leantime
version: 0.0.8
annotations:
  truecharts.org/catagories: |
    - management
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
