apiVersion: v2
appVersion: "2.7.3"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Keep track of your network latency.
home: https://github.com/truecharts/apps/tree/master/charts/stable/smokeping
icon: https://github.com/truecharts/apps/raw/main/images/smokeping.png
keywords:
- smokeping
- network
- latency
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: smokeping
sources:
- https://oss.oetiker.ch/smokeping/
- https://hub.docker.com/r/linuxserver/smokeping
type: application
version: 1.0.21
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
