apiVersion: v2
appVersion: "6.2.6"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Open source, advanced key-value store.
home: https://github.com/truecharts/apps/tree/master/stable/redis
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
  - redis
  - keyvalue
  - database
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: redis
sources:
  - https://github.com/bitnami/bitnami-docker-redis
  - http://redis.io/
type: application
version: 1.0.29
annotations:
  truecharts.org/catagories: |
    - database
    - cache
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
