apiVersion: v2
appVersion: "6.2"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: Web-Based postgresql database management utility
home: https://github.com/truecharts/apps/tree/master/charts/stable/pgadmin
icon: https://www.postgresql.org/message-id/attachment/1139/pgAdmin.svg
keywords:
- pgadmin
- db
- database
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pgadmin
sources:
- https://www.pgadmin.org/
type: application
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - management
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
