apiVersion: v2
appVersion: "2021.10.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: DNS and Ad-filtering for your network
home: https://github.com/truecharts/apps/tree/master/charts/stable/pihole
icon: https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Pi-hole_vector_logo.svg/1200px-Pi-hole_vector_logo.svg.png
keywords:
- DNS
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pihole
sources:
- https://pi-hole.net/
- https://github.com/pi-hole
- https://github.com/pi-hole/docker-pi-hole
type: application
version: 4.0.21
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
