apiVersion: v2
appVersion: "0.5.4"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend
home: https://github.com/truecharts/apps/tree/master/charts/stable/mealie
icon: https://raw.githubusercontent.com/hay-kot/mealie/gh-pages/assets/img/favicon.png
keywords:
- grocy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mealie
sources:
- https://github.com/hay-kot/mealie
version: 4.0.20
annotations:
  truecharts.org/catagories: |
    - utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
