apiVersion: v2
appVersion: "5.32.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Calibre is a powerful and easy to use e-book manager.
home: https://github.com/truechartsapps/tree/master/charts/stable/calibre
icon: https://github.com/kovidgoyal/calibre/raw/master/resources/images/lt.png
keywords:
- calibre
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: calibre
sources:
- https://hub.docker.com/r/linuxserver/calibre/
- https://github.com/kovidgoyal/calibre/
version: 4.0.22
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
