apiVersion: v2
appVersion: "7.3.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Professional Photo Management with the Power of Open Source
home: https://github.com/truecharts/apps/tree/master/charts/stable/digikam
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/digikam.png
keywords:
- digikam
- photo
- management
- image
- gallery
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: digikam
sources:
- https://github.com/linuxserver/docker-digikam
- https://www.digikam.org/
type: application
version: 2.0.21
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
