apiVersion: v2
appVersion: "3.13.6"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: TeamSpeak is software for quality voice communication via the Internet.
home: https://github.com/truecharts/apps/tree/master/charts/stable/teamspeak3
icon: https://raw.githubusercontent.com/docker-library/docs/618191cf82de051ff6661c3c8b82cfca1b663972/teamspeak/logo.png
keywords:
- voice server
- teamspeak
- teamspeak3
- teamspeak server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: teamspeak3
sources:
- https://hub.docker.com/_/teamspeak
- https://www.teamspeak.com/en/
type: application
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - voice
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
