apiVersion: v2
appVersion: "1.8.10"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Container for protonmail bridge to work on the network.
home: https://github.com/truechartsapps/tree/master/charts/stable/protonmail-bridge
icon: https://raw.githubusercontent.com/ProtonMail/proton-bridge/master/icon.iconset/icon_256x256.png
keywords:
- protonmail
- protonmail-bridge
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: protonmail-bridge
sources:
- https://github.com/shenxn/protonmail-bridge-docker
- https://hub.docker.com/r/shenxn/protonmail-bridge
version: 4.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
