apiVersion: v2
appVersion: "0.52.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
- condition: exporters.enabled,exporters.node-exporter.enabled
  name: node-exporter
  repository: https://charts.bitnami.com/bitnami
  version: 2.3.17
- condition: exporters.enabled,exporters.kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://charts.bitnami.com/bitnami
  version: 2.1.18
deprecated: false
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
home: https://github.com/truecharts/apps/tree/master/charts/stable/prometheus
keywords:
- metrics
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: prometheus
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
type: application
version: 1.1.11
annotations:
  truecharts.org/catagories: |
    - metrics
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
