apiVersion: v2
appVersion: "2021.09.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
deprecated: false
description: DeepStack AI provides AI features including Face Recognition, Object
  Detection, Scene Recognition and custom AI Models
home: https://github.com/truecharts/apps/tree/master/charts/stable/deepstack-gpu
icon: https://deepquest.sfo2.digitaloceanspaces.com/deepstackcc/static/img/deepstacklogo.png
keywords:
- AI
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: deepstack-gpu
sources:
- https://github.com/johnolafenwa/DeepStack
- https://hub.docker.com/r/deepquestai/deepstack
- https://www.deepstack.cc/
type: application
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - AI
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
