apiVersion: v2
appVersion: "2.2.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: An FTP automation tool that periodically scans given host locations for
  new files.
home: https://github.com/truecharts/apps/tree/master/charts/stable/davos
icon: https://github.com/linuxserver/davos/raw/master/src/main/resources/static/android-chrome-192x192.png
keywords:
- davos
- ftp
- automation
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: davos
sources:
- https://github.com/linuxserver/docker-davos
- https://github.com/linuxserver/davos/
type: application
version: 2.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
