apiVersion: v2
appVersion: "2021.5.10"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: An Automatic Video Library Manager for TV Shows
home: https://github.com/truecharts/apps/tree/master/charts/stable/sickchill
icon: https://github.com/SickChill/SickChill/raw/master/sickchill/gui/slick/images/ico/android-chrome-256x256.png
keywords:
- sickchill
- video
- library
- manager
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sickchill
sources:
- https://github.com/linuxserver/docker-sickchill
- https://github.com/SickChill/SickChill
type: application
version: 1.0.19
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
