apiVersion: v2
appVersion: "0.1.7.1199"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.15
description: Indexer manager/proxy built on the popular arr net base stack to integrate
  with your various PVR apps.
home: https://github.com/truecharts/apps/tree/master/charts/stable/prowlarr
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png
keywords:
- prowlarr
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: prowlarr
sources:
- https://github.com/Prowlarr/Prowlarr
- https://github.com/k8s-at-home/container-images
version: 4.0.31
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
